spring.application.name=backend

spring.datasource.url =jdbc:postgresql://localhost:5432/skymind_ai
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080


aviationstack.api.key=4f0628403aaf8bfd6ecfb86411751443
aviationstack.base.url=https://api.aviationstack.com/v1



spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=llama3.1:8b

