spring.application.name=backend

server.port=8080

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/skymind_ai}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

aviationstack.api.key=${AVIATIONSTACK_API_KEY:XXXXXXXXXXXXXXXXXXXXX}
aviationstack.base.url=https://api.aviationstack.com/v1

spring.ai.ollama.base-url=${OLLAMA_BASE_URL:http://localhost:11434}
spring.ai.ollama.chat.model=llama3.1:8b